export interface Product {
  id: string
  slug: string
  name: string
  latinName?: string
  category: string
  categorySlug: string
  description: string
  image: string
  tags: string[]
  origin: string
  type: "frais" | "surgelé" | "frais-surgelé"
  caliber?: string
  usage: string[]
  formats: string[]
  isBestSeller?: boolean
  priceIndicatif?: string
}

export const categories = [
  { slug: "crevettes-crustaces", name: "Crevettes & crustacés", icon: "shrimp" },
  { slug: "calamars-poulpes", name: "Calamars & poulpes", icon: "octopus" },
  { slug: "mollusques", name: "Mollusques", icon: "shell" },
  { slug: "poissons-mediterranee", name: "Poissons Méditerranée", icon: "fish" },
  { slug: "saumon-thon", name: "Saumon & thon", icon: "fish" },
  { slug: "caviar-haute-gastronomie", name: "Caviar & haute gastronomie", icon: "sparkles" },
]

export const products: Product[] = [
  // CREVETTES & CRUSTACÉS
  {
    id: "1",
    slug: "crevettes-blanches-entieres-20-30",
    name: "Crevettes blanches entières 20/30",
    latinName: "Penaeus spp.",
    category: "Crevettes & crustacés",
    categorySlug: "crevettes-crustaces",
    description:
      "Crevettes blanches entières de Méditerranée, calibre 20/30. Chair ferme et douce, idéales pour grillades, plancha et fritures.",
    image: "/products/crevettes-blanches-entieres-20-30.jpg",
    tags: ["Premium", "HORECA", "Export"],
    origin: "Méditerranée",
    type: "frais-surgelé",
    caliber: "20/30",
    usage: ["Restaurants", "Hôtels", "Traiteurs"],
    formats: ["Carton 2kg", "Carton 5kg", "Carton 10kg"],
    isBestSeller: true,
    priceIndicatif: "14,50 DT / kg",
  },
  {
    id: "2",
    slug: "crevettes-blanches-entieres-mix",
    name: "Crevettes blanches entières mix calibres",
    latinName: "Penaeus spp.",
    category: "Crevettes & crustacés",
    categorySlug: "crevettes-crustaces",
    description:
      "Sélection de crevettes blanches entières, calibrage 60/70 à 10/20. Solution flexible pour buffets et volumes importants.",
    image: "/products/crevettes-blanches-entieres-mix.jpg",
    tags: ["HORECA", "Export"],
    origin: "Méditerranée",
    type: "frais-surgelé",
    caliber: "60/70 – 10/20",
    usage: ["Buffets", "Restauration collective", "Grossistes"],
    formats: ["Carton 5kg", "Carton 10kg"],
    priceIndicatif: "Sur demande",
  },
  {
    id: "3",
    slug: "crevettes-blanches-decortiquees",
    name: "Crevettes blanches décortiquées",
    latinName: "Penaeus spp.",
    category: "Crevettes & crustacés",
    categorySlug: "crevettes-crustaces",
    description:
      "Crevettes blanches décortiquées IQF, prêtes à l'emploi. Idéales pour pâtes, poêlées, sauces et cuisine rapide.",
    image: "/products/crevettes-blanches-decortiquees.jpg",
    tags: ["Prêt à l'emploi", "HORECA"],
    origin: "Méditerranée",
    type: "surgelé",
    caliber: "60/70 – 30/40",
    usage: ["Restaurants", "Traiteurs", "Snacking haut de gamme"],
    formats: ["Sachet 1kg", "Carton 5kg"],
    priceIndicatif: "Sur demande",
  },
  {
    id: "4",
    slug: "crevettes-rouges-entieres",
    name: "Crevettes rouges entières",
    latinName: "Aristeus antennatus",
    category: "Crevettes & crustacés",
    categorySlug: "crevettes-crustaces",
    description:
      "Crevettes rouges sauvages de Méditerranée. Couleur vive, texture exceptionnelle. Un produit d'exception pour établissements premium.",
    image: "/products/crevettes-rouges-entieres.jpg",
    tags: ["Premium", "Gastronomie"],
    origin: "Méditerranée",
    type: "frais-surgelé",
    caliber: "60/70 – 10/20",
    usage: ["Restaurants gastronomiques", "Hôtels 5 étoiles"],
    formats: ["Carton 2kg", "Carton 5kg"],
    isBestSeller: true,
    priceIndicatif: "22,00 DT / kg",
  },
  {
    id: "5",
    slug: "crevettes-rouges-decortiquees",
    name: "Crevettes rouges décortiquées",
    latinName: "Aristeus antennatus",
    category: "Crevettes & crustacés",
    categorySlug: "crevettes-crustaces",
    description:
      "Crevettes rouges décortiquées, qualité premium. Idéales pour plats signatures, risottos et préparations raffinées.",
    image: "/products/crevettes-rouges-decortiquees.jpg",
    tags: ["Premium", "HORECA"],
    origin: "Méditerranée",
    type: "surgelé",
    caliber: "60/70 – 30/40",
    usage: ["Restaurants gastronomiques", "Catering haut de gamme"],
    formats: ["Sachet 1kg", "Carton 5kg"],
    priceIndicatif: "Sur demande",
  },
  {
    id: "6",
    slug: "langouste-roche",
    name: "Langouste de roche",
    latinName: "Palinurus elephas",
    category: "Crevettes & crustacés",
    categorySlug: "crevettes-crustaces",
    description:
      "Langouste de roche entière, produit de prestige à chair blanche ferme. Idéale pour plateaux de fruits de mer et menus gastronomiques.",
    image: "/products/langouste-roche.jpg",
    tags: ["Prestige", "Gastronomie"],
    origin: "Méditerranée",
    type: "surgelé",
    usage: ["Restaurants gastronomiques", "Hôtels de luxe"],
    formats: ["Pièce entière surgelée", "Carton export"],
    priceIndicatif: "Sur demande",
  },
  {
    id: "7",
    slug: "crabe-bleu-entier",
    name: "Crabe bleu entier",
    latinName: "Callinectes sapidus",
    category: "Crevettes & crustacés",
    categorySlug: "crevettes-crustaces",
    description:
      "Crabe bleu entier, chair sucrée et parfumée. Rendement élevé en chair, prisé pour la cuisine gastronomique.",
    image: "/products/crabe-bleu-entier.jpg",
    tags: ["Premium", "Export"],
    origin: "Méditerranée",
    type: "surgelé",
    usage: ["Restaurants", "Traiteurs", "Cuisine créative"],
    formats: ["Carton 5kg", "Carton 10kg"],
    priceIndicatif: "Sur demande",
  },
  {
    id: "8",
    slug: "pattes-crabe-bleu",
    name: "Pattes de crabe bleu",
    latinName: "Callinectes sapidus",
    category: "Crevettes & crustacés",
    categorySlug: "crevettes-crustaces",
    description:
      "Pattes de crabe bleu riches en chair, faciles à décortiquer. Idéales pour entrées, salades et buffets.",
    image: "/products/pattes-crabe-bleu.jpg",
    tags: ["HORECA"],
    origin: "Méditerranée",
    type: "surgelé",
    usage: ["Restaurants", "Buffets", "Traiteurs"],
    formats: ["Sachet 1kg", "Carton 5kg"],
    priceIndicatif: "Sur demande",
  },

  // CALAMARS & POULPES
  {
    id: "9",
    slug: "calmar-entier-standardise",
    name: "Calmar entier standardisé",
    latinName: "Loligo vulgaris",
    category: "Calamars & poulpes",
    categorySlug: "calamars-poulpes",
    description:
      "Calmar entier nettoyé, calibres unifiés 30/20, 40/30, 50/40. Adapté aux marchés export et à la restauration.",
    image: "/products/calmar-entier.jpg",
    tags: ["Export", "Standardisé"],
    origin: "Méditerranée",
    type: "frais-surgelé",
    caliber: "30/20 – 50/40",
    usage: ["Restaurants", "Traiteurs", "Industrie"],
    formats: ["Carton 10kg IQF"],
    priceIndicatif: "Sur demande",
  },
  {
    id: "10",
    slug: "calamars-tubes-prets-farcir",
    name: "Calamars tubes prêts à farcir",
    latinName: "Loligo vulgaris",
    category: "Calamars & poulpes",
    categorySlug: "calamars-poulpes",
    description:
      "Tubes de calamars nettoyés, prêts à farcir ou à détailler en anneaux. Gain de temps en cuisine professionnelle.",
    image: "/products/calamars-tubes.jpg",
    tags: ["HORECA", "Prêt à l'emploi"],
    origin: "Méditerranée",
    type: "surgelé",
    usage: ["Restaurants", "Traiteurs", "Événementiel"],
    formats: ["Carton 2kg", "Carton 5kg"],
    isBestSeller: true,
    priceIndicatif: "12,50 DT / kg",
  },
  {
    id: "11",
    slug: "oeufs-de-calmar",
    name: "Œufs de calmar",
    latinName: "Loligo vulgaris",
    category: "Calamars & poulpes",
    categorySlug: "calamars-poulpes",
    description:
      "Œufs de calmar frais ou surgelés, produit rare et recherché pour recettes gastronomiques et menus créatifs.",
    image: "/products/oeufs-calmar.jpg",
    tags: ["Rare", "Gastronomie"],
    origin: "Méditerranée",
    type: "frais-surgelé",
    usage: ["Restaurants gastronomiques", "Hôtels"],
    formats: ["Barquette 500g", "Barquette 1kg"],
    priceIndicatif: "Sur demande",
  },
  {
    id: "12",
    slug: "poulpe-mediterranee-entier",
    name: "Poulpe Méditerranée entier",
    latinName: "Octopus vulgaris",
    category: "Calamars & poulpes",
    categorySlug: "calamars-poulpes",
    description: "Poulpe méditerranéen entier, nettoyé et prêt à cuire. Chair tendre après cuisson, goût authentique.",
    image: "/products/poulpe-mediterranee-entier.jpg",
    tags: ["Best-seller", "Export"],
    origin: "Méditerranée",
    type: "surgelé",
    usage: ["Restaurants", "Traiteurs", "Distribution"],
    formats: ["Individuel 1–2kg", "Carton 5kg", "Carton 10kg"],
    isBestSeller: true,
    priceIndicatif: "16,00 DT / kg",
  },
  {
    id: "13",
    slug: "poulpe-tentacules-coupees",
    name: "Tentacules de poulpe coupées",
    latinName: "Octopus vulgaris",
    category: "Calamars & poulpes",
    categorySlug: "calamars-poulpes",
    description:
      "Tentacules de poulpe coupées en morceaux 5–7 cm, surgelées IQF. Idéales pour grillades, tapas et salades.",
    image: "/products/poulpe-tentacules.jpg",
    tags: ["Prêt à l'emploi", "HORECA"],
    origin: "Méditerranée",
    type: "surgelé",
    usage: ["Restaurants", "Bar à tapas", "Traiteurs"],
    formats: ["Sachet 1kg", "Carton 5kg"],
    priceIndicatif: "Sur demande",
  },

  // MOLLUSQUES
  {
    id: "14",
    slug: "moules-noires-mediterranee",
    name: "Moules noires de Méditerranée",
    latinName: "Mytilus galloprovincialis",
    category: "Mollusques",
    categorySlug: "mollusques",
    description: "Moules noires fraîches ou surgelées, nettoyées et ébarbées. Chair généreuse et saveur iodée.",
    image: "/products/moules-noires.jpg",
    tags: ["HORECA"],
    origin: "Méditerranée",
    type: "frais-surgelé",
    usage: ["Restaurants", "Brasseries", "Traiteurs"],
    formats: ["Filet 2kg", "Carton 10kg"],
    priceIndicatif: "4,50 DT / kg",
  },
  {
    id: "15",
    slug: "huitres-mediterranee",
    name: "Huîtres",
    latinName: "Crassostrea gigas",
    category: "Mollusques",
    categorySlug: "mollusques",
    description: "Huîtres élevées en fermes marines contrôlées. Idéales pour plateaux de fruits de mer et événements.",
    image: "/products/huitres.jpg",
    tags: ["Premium"],
    origin: "Fermes marines contrôlées",
    type: "frais",
    usage: ["Restaurants", "Hôtels", "Événementiel"],
    formats: ["Bourriche 12", "Bourriche 24", "Bourriche 48"],
    priceIndicatif: "Sur demande",
  },
  {
    id: "16",
    slug: "oursins-mediterranee",
    name: "Oursins de mer",
    latinName: "Paracentrotus lividus",
    category: "Mollusques",
    categorySlug: "mollusques",
    description: "Oursins de mer méditerranéens récoltés manuellement, gonades crémeuses pour préparations raffinées.",
    image: "/products/oursins.jpg",
    tags: ["Saisonnier", "Gastronomie"],
    origin: "Méditerranée",
    type: "frais",
    usage: ["Restaurants gastronomiques", "Bars à huîtres"],
    formats: ["Caisse isotherme"],
    priceIndicatif: "Sur demande",
  },

  // POISSONS MÉDITERRANÉE
  {
    id: "17",
    slug: "loup-de-mer-tunisie",
    name: "Loup de Mer",
    latinName: "Dicentrarchus labrax",
    category: "Poissons Méditerranée",
    categorySlug: "poissons-mediterranee",
    description: "Loup de mer de Méditerranée, symbole de la gastronomie. Chair blanche ferme et saveur subtile.",
    image: "/products/loup-de-mer.jpg",
    tags: ["Premium", "HORECA"],
    origin: "Tunisie",
    type: "frais-surgelé",
    caliber: "400–600g, 600–800g, 800–1200g",
    usage: ["Restaurants", "Hôtels", "Événementiel"],
    formats: ["Caisse glace", "Carton 10kg"],
    isBestSeller: true,
    priceIndicatif: "13,50 DT / kg",
  },
  {
    id: "18",
    slug: "dorade-royale-mediterranee",
    name: "Dorade royale",
    latinName: "Sparus aurata",
    category: "Poissons Méditerranée",
    categorySlug: "poissons-mediterranee",
    description: "Dorade royale de Méditerranée, chair fine et délicate. Présentation parfaite pour service en salle.",
    image: "/products/dorade-royale.jpg",
    tags: ["Premium", "HORECA"],
    origin: "Méditerranée",
    type: "frais-surgelé",
    caliber: "300–400g, 400–600g",
    usage: ["Restaurants gastronomiques", "Hôtels"],
    formats: ["Caisse glace", "Carton 10kg"],
    priceIndicatif: "11,00 DT / kg",
  },
  {
    id: "19",
    slug: "dorade-elevage-mediterranee",
    name: "Dorade d'élevage",
    latinName: "Sparus aurata",
    category: "Poissons Méditerranée",
    categorySlug: "poissons-mediterranee",
    description: "Dorade d'élevage au calibrage précis, idéale pour chaînes de restauration et distribution.",
    image: "/products/dorade-elevage.jpg",
    tags: ["Élevage contrôlé"],
    origin: "Élevage Méditerranée",
    type: "frais-surgelé",
    usage: ["Restaurants", "Distribution"],
    formats: ["Calibres HORECA", "Conditionnement sous-vide"],
    priceIndicatif: "Sur demande",
  },
  {
    id: "20",
    slug: "bar-elevage-mediterranee",
    name: "Bar d'élevage",
    latinName: "Dicentrarchus labrax",
    category: "Poissons Méditerranée",
    categorySlug: "poissons-mediterranee",
    description: "Bar d'élevage homogène, texture régulière. Adapté aux volumes stables et chaînes de restauration.",
    image: "/products/bar-elevage.jpg",
    tags: ["Élevage", "HORECA"],
    origin: "Élevage Méditerranée",
    type: "frais-surgelé",
    usage: ["Restaurants", "Distribution"],
    formats: ["Portions calibrées", "Caisse glace"],
    priceIndicatif: "Sur demande",
  },
  {
    id: "21",
    slug: "sole-mediterranee",
    name: "Sole",
    latinName: "Solea solea",
    category: "Poissons Méditerranée",
    categorySlug: "poissons-mediterranee",
    description: "Sole de Méditerranée, poisson plat très apprécié. Chair blanche fine pour cuisine gastronomique.",
    image: "/products/sole.jpg",
    tags: ["Poisson plat", "Gastronomie"],
    origin: "Méditerranée",
    type: "frais-surgelé",
    usage: ["Restaurants", "Hôtels"],
    formats: ["Caisse glace", "Carton 10kg"],
    priceIndicatif: "Sur demande",
  },
  {
    id: "22",
    slug: "merou-hammour",
    name: "Mérou / Hammour",
    latinName: "Epinephelus marginatus",
    category: "Poissons Méditerranée",
    categorySlug: "poissons-mediterranee",
    description:
      "Mérou (Hammour), poisson noble à chair épaisse. Très apprécié pour plats signature et cuisine moyen-orientale.",
    image: "/products/merou-hammour.jpg",
    tags: ["Noble", "Premium"],
    origin: "Méditerranée",
    type: "frais-surgelé",
    usage: ["Restaurants haut de gamme", "Hôtels"],
    formats: ["Poissons entiers", "Portions sur commande"],
    priceIndicatif: "Sur demande",
  },
  {
    id: "23",
    slug: "poisson-corail",
    name: "Poisson corail",
    latinName: "Cephalopholis miniata",
    category: "Poissons Méditerranée",
    categorySlug: "poissons-mediterranee",
    description: "Poisson corail de profondeur, chair blanche avec peu d'arêtes. Segment premium pour export.",
    image: "/products/poisson-corail.jpg",
    tags: ["Profondeur", "Premium"],
    origin: "Méditerranée",
    type: "surgelé",
    usage: ["Export", "Restaurants"],
    formats: ["Carton 10kg"],
    priceIndicatif: "Sur demande",
  },
  {
    id: "24",
    slug: "sbarus-mediterranee",
    name: "Sbarus",
    latinName: "Diplodus sargus",
    category: "Poissons Méditerranée",
    categorySlug: "poissons-mediterranee",
    description: "Sbarus, poisson blanc à chair ferme. Idéal pour friture, grillades et cuisine familiale.",
    image: "/products/sbarus.jpg",
    tags: ["Traditionnel"],
    origin: "Méditerranée",
    type: "frais-surgelé",
    usage: ["Restaurants", "Poissonneries"],
    formats: ["Caisse glace"],
    priceIndicatif: "Sur demande",
  },
  {
    id: "25",
    slug: "sardines-fraiches-mediterranee",
    name: "Sardines fraîches",
    latinName: "Sardina pilchardus",
    category: "Poissons Méditerranée",
    categorySlug: "poissons-mediterranee",
    description:
      "Sardines fraîches de Méditerranée, pêche du jour. Idéales pour grillades, fritures et conserves artisanales.",
    image: "/products/sardines-fraiches.jpg",
    tags: ["Export", "Distribution"],
    origin: "Tunisie",
    type: "frais",
    usage: ["Restaurants", "Poissonneries", "Conserveries"],
    formats: ["Caisse 5kg", "Caisse 10kg"],
    priceIndicatif: "3,50 DT / kg",
  },
  {
    id: "26",
    slug: "sultan-ibrahim-rouget",
    name: "Sultan Ibrahim / Rouget",
    latinName: "Mullus barbatus",
    category: "Poissons Méditerranée",
    categorySlug: "poissons-mediterranee",
    description:
      "Sultan Ibrahim (rouget), poisson coloré très apprécié. Chair fine, idéale pour cuisine méditerranéenne.",
    image: "/products/sultan-ibrahim.jpg",
    tags: ["Coloré", "Gastronomie"],
    origin: "Méditerranée",
    type: "frais-surgelé",
    usage: ["Restaurants", "Hôtels"],
    formats: ["Caisse glace", "Carton 10kg"],
    priceIndicatif: "Sur demande",
  },
  {
    id: "27",
    slug: "anguille-de-mer",
    name: "Anguille de mer",
    latinName: "Conger conger",
    category: "Poissons Méditerranée",
    categorySlug: "poissons-mediterranee",
    description: "Anguille de mer, chair blanche parfumée. Utilisée pour recettes traditionnelles et fumage.",
    image: "/products/anguille-mer.jpg",
    tags: ["Spécialité"],
    origin: "Méditerranée",
    type: "frais-surgelé",
    usage: ["Restaurants", "Fumaison artisanale"],
    formats: ["Pièces entières", "Tronçons"],
    priceIndicatif: "Sur demande",
  },

  // SAUMON & THON
  {
    id: "28",
    slug: "bloc-thon-sushi",
    name: "Bloc de thon",
    latinName: "Thunnus albacares",
    category: "Saumon & thon",
    categorySlug: "saumon-thon",
    description:
      "Bloc de thon désossé, surgelé à très basse température. Idéal pour sushi, sashimi et industrie des produits de la mer.",
    image: "/products/bloc-thon.jpg",
    tags: ["Sushi", "Industrie"],
    origin: "Méditerranée / Océan",
    type: "surgelé",
    usage: ["Restaurants japonais", "Industrie", "Gastronomie"],
    formats: ["Blocs sous-vide", "Carton export"],
    priceIndicatif: "Sur demande",
  },
  {
    id: "29",
    slug: "filets-saumon-atlantique",
    name: "Filets de saumon Atlantique",
    latinName: "Salmo salar",
    category: "Saumon & thon",
    categorySlug: "saumon-thon",
    description:
      "Filets de saumon Atlantique d'élevage norvégien, désarêtés. Chair rosée et fondante, riche en oméga-3.",
    image: "/products/filets-saumon.jpg",
    tags: ["Best-seller", "Export"],
    origin: "Norvège",
    type: "frais-surgelé",
    usage: ["Restaurants", "Hôtels", "Distribution"],
    formats: ["Filet 1–1,5kg", "Filet 1,5–2kg"],
    isBestSeller: true,
    priceIndicatif: "18,00 DT / kg",
  },
  {
    id: "30",
    slug: "portions-saumon-pretes-a-cuire",
    name: "Portions de saumon prêtes à cuire",
    latinName: "Salmo salar",
    category: "Saumon & thon",
    categorySlug: "saumon-thon",
    description:
      "Portions de saumon calibrées pour une cuisson rapide et régulière. Idéales pour restauration et retail.",
    image: "/products/portions-saumon.jpg",
    tags: ["Prêt à cuire", "HORECA"],
    origin: "Norvège",
    type: "surgelé",
    usage: ["Restaurants", "Hôtels", "Distribution"],
    formats: ["Portions 120g", "Portions 150g"],
    priceIndicatif: "Sur demande",
  },
  {
    id: "31",
    slug: "saumon-norvegien-frais",
    name: "Saumon norvégien frais",
    latinName: "Salmo salar",
    category: "Saumon & thon",
    categorySlug: "saumon-thon",
    description:
      "Saumon norvégien frais, suivi de chaîne du froid. Destiné aux restaurants, fumage et ateliers de découpe.",
    image: "/products/saumon-norvegien-frais.jpg",
    tags: ["Import", "Premium"],
    origin: "Norvège",
    type: "frais",
    usage: ["Restaurants", "Fumaison", "Catering"],
    formats: ["Poisson entier", "Gros tronçons"],
    priceIndicatif: "Sur demande",
  },
  {
    id: "32",
    slug: "thon-rouge-mediterranee-sashimi",
    name: "Thon rouge de Méditerranée",
    latinName: "Thunnus thynnus",
    category: "Saumon & thon",
    categorySlug: "saumon-thon",
    description:
      "Thon rouge de Méditerranée, pêche responsable. Qualité sashimi pour les établissements les plus exigeants.",
    image: "/products/thon-rouge-mediterranee.jpg",
    tags: ["Premium", "Sashimi"],
    origin: "Méditerranée",
    type: "frais",
    usage: ["Restaurants japonais", "Gastronomie"],
    formats: ["Longe", "Blocs sur commande"],
    priceIndicatif: "65,00 DT / kg",
  },

  // CAVIAR & HAUTE GASTRONOMIE
  {
    id: "33",
    slug: "caviar-osetra-haute-gastronomie",
    name: "Caviar Osetra",
    latinName: "Acipenser gueldenstaedtii",
    category: "Caviar & haute gastronomie",
    categorySlug: "caviar-haute-gastronomie",
    description:
      "Caviar Osetra d'élevage contrôlé, grains dorés à ambrés. Notes de noisette et finale longue en bouche.",
    image: "/products/caviar-osetra.jpg",
    tags: ["Luxe", "Premium"],
    origin: "Élevage contrôlé",
    type: "frais-surgelé",
    usage: ["Restaurants étoilés", "Hôtels de luxe", "Événementiel VIP"],
    formats: ["Boîte 30g", "Boîte 50g", "Boîte 100g", "Boîte 250g"],
    isBestSeller: true,
    priceIndicatif: "1 200,00 DT / kg",
  },
  {
    id: "34",
    slug: "caviar-beluga-ultra-premium",
    name: "Caviar Beluga",
    latinName: "Huso huso",
    category: "Caviar & haute gastronomie",
    categorySlug: "caviar-haute-gastronomie",
    description:
      "Caviar Beluga ultra-premium, perles noires larges et soyeuses. Produit emblématique des cartes de luxe.",
    image: "/products/caviar-beluga.jpg",
    tags: ["Ultra-premium", "Luxe"],
    origin: "Élevage contrôlé",
    type: "frais-surgelé",
    usage: ["Palaces", "Restaurants étoilés", "Événements VIP"],
    formats: ["Boîte 30g", "Boîte 50g", "Boîte 100g", "Boîte 250g"],
    priceIndicatif: "Sur demande",
  },
  {
    id: "35",
    slug: "caviar-siberian-baikal",
    name: "Caviar Siberian / Baïkal",
    latinName: "Acipenser baerii",
    category: "Caviar & haute gastronomie",
    categorySlug: "caviar-haute-gastronomie",
    description: "Caviar Siberian / Baïkal, perles fraîches à l'équilibre parfait entre douceur et salinité.",
    image: "/products/caviar-siberian.jpg",
    tags: ["Premium"],
    origin: "Élevage contrôlé",
    type: "frais-surgelé",
    usage: ["Restaurants gastronomiques", "Bars à caviar"],
    formats: ["Boîte 30g", "Boîte 50g", "Boîte 100g"],
    priceIndicatif: "Sur demande",
  },
]

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.categorySlug === categorySlug)
}

export function getBestSellers(): Product[] {
  return products.filter((p) => p.isBestSeller)
}
